config/routes.rb
Timetracker::Application.routes.draw do
  devise_for :users
  root "companies#index"
  get "recentworks/:days", to: "works#index"
  get "timetracker/:slug", to: "projects#show"
  resources :works
  resources :projects
  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :users
  has_many :projects

  validates :name, length: { minimum: 5 }

  def to_s
    name
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :company
  has_many :works
  has_many :users, through: :works
  belongs_to :user

  validates :name, presence: true, length: { minimum: 5 }
  validates_presence_of :company
  validates :default_rate, numericality: { only_integer: true, greater_than_or_equal_to: 50 }
  validates :slug, uniqueness: true, length: { minimum: 3 }

  scope :low_default_rate, -> { where("default_rate < ?", 100)}

  def to_s
    "#{name} (#{company.name})"
  end

  def self.export_csv projects
    CSV.generate() do |csv|
      csv << ["name", "company", "default_rate", "created_at", "owner", "most_recent_work_item"]
      projects.each do |project|
        csv << [
                project.name,
                project.company,
                project.default_rate,
                project.created_at,
                project.user,
                project.works.last
                ]
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :company
  has_many :works
  has_many :projects, through: :works
  has_many :projects
  
  validates :first_name, length: { minimum: 2}
  validates :last_name, length: { minimum: 5}
  validates_presence_of :company

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/work.rb
class Work < ActiveRecord::Base
  belongs_to :project
  belongs_to :user

  validates :hours, numericality: { only_integer: true, greater_than: 0 }
  validates_presence_of :project, :user, :date_time_performed
  validate :date_time_cannot_be_in_the_future
  validates :hours, length: { in: 1..8 }
  scope :fullday, -> { where("hours >= 8") }
  scope :order_by_time, -> { order('date_time_performed DESC') }
  #scope :recent, -> { where("date_time_performed > '#{Time.now - 7.days}'")}

  def self.recent_works number_of_days_ago
    since_date = Time.now - number_of_days_ago.to_i.days
    where("date_time_performed > '#{since_date}'")
  end

  def to_s
    "#{user}: #{date_time_performed.strftime('%d/%m/%Y %H:%M')} - #{hours} hours"
  end

  private
    def date_time_cannot_be_in_the_future
      if date_time_performed.present? && date_time_performed > Time.now
        errors.add(:date_time_performed, "can't be in future")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   before_action :configure_permitted_parameters, if: :devise_controller?

def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email) }
  devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :company_id, :email, :password, :password_confirmation) }
  devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:first_name, :last_name, :company_id,:name, :email, :password, :password_confirmation, :current_password) }
end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :edit, :update, :new]
  before_filter :is_admin?, only: [:create, :edit, :update, :new]
  def index
    @companies = Company.all    
  end

  def show
    @company = Company.find(params[:id])
    respond_to do |format|
      format.html 
      format.xml   { render xml: @company }
      format.json  { render json: @company }
    end
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(secure_params)
    if @company.save
      redirect_to root_path, notice: "Companies was created"
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if @company.update_attributes(secure_params)
      redirect_to @company, notice: "Update succesfull"
    else
      redirect_to edit_company_path(@company), alert: "Something goes wrong"
    end
  end

  private
    def secure_params
      params.require(:company).permit(:name)
    end

    def is_admin?
      unless current_user.admin?
        redirect_to root_path, alert: "Only admin can do this!"
      end
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @projects = Project.all
    respond_to do |format|
      format.html
      format.csv { send_data Project.export_csv(@projects), type: 'text/csv; charset=utf-8; header-present;', disposition: 'attachment; filename=contacts.csv'}
    end
  end

  def show
    if params[:slug]
      @project = Project.find_by slug: params[:slug]
    else
      @project = Project.find(params[:id])
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(secure_params)
    if @project.save
      redirect_to root_path, notice: "Project was created"
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(secure_params)
      Usermailer.update_project(@project).deliver
      redirect_to @project, notice: "Update succesfull"
    else
      redirect_to edit_project_path(@project), alert: "Something goes wrong"
    end
  end
  private
    def secure_params
      params.require(:project).permit(:name, :slug, :default_rate, :company_id)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_filter :authentcate_user!, only: [:new, :create, :edit, :update]
  def index
    if params[:days]
      @works = Work.all.recent_works(params[:days]).order_by_time.paginate(page: params[:page])
    else
      @works = Work.all.order_by_time.paginate(page: params[:page])
    end
  end

  def show
    @work = Work.find(params[:id])
  end

  def new
    @work = Work.new
  end

  def create
    @work = Work.new(secure_params)
    @work.user = current_user
    uploaded_io = params[:work][:doc]

    if uploaded_io
      File.open(Rails.root.join("public", "uploads", uploaded_io.original_filename), 'wb') do |file|
        file.write(uploaded_io.read)
        @work.doc = uploaded_io.original_filename
      end
    end

    if @work.save
      Usermailer.send_info_about_work(@work).deliver
      redirect_to root_path
    else
      render :new
    end
  end

  def edit
    @work = Work.find(params[:id])
  end

  def update
    @work = Work.find(params[:id])
    @work.user = current_user
    if @work.update_attributes(secure_params)
      redirect_to @work, notice: "Update succesfull"
    else
      redirect_to edit_work_path(@work), alert: "Something goes wrong"
    end
  end
  private
    def secure_params
      params.require(:work).permit(:project_id, :user_id, :date_time_performed, :hours)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def nav_items
    [
      {
        display_text: "Companies",
        controller_name: "companies",
        url_path: companies_path },
      {
        display_text: "Projects",
        controller_name: "projects",
        url_path: projects_path },
      {
        display_text: "Works",
        controller_name: "works",
        url_path: works_path }
    ]
  end

  def display_nav_item(display_text, controller_name_p, url_path)
    raw("<li #{controller_name == controller_name_p ? 'class="active"' : ''}>#{link_to display_text, url_path}</li>")
  end

  def display_login_messages
    if user_signed_in?
      raw("<p>#{current_user}<br/>#{link_to 'Logout', destroy_user_session_path, method: :delete, confirm: 'Are you sure?'} </p>")
    else
      #Login | Register

      raw("<p>#{link_to 'Login', new_user_session_path} | #{link_to 'Register', new_user_registration_path}</p>")
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/companies/_company.html.haml
%tr
  %td= link_to company, company

app/views/companies/_form.html.haml
= simple_form_for(@company, defaults: { input_html: { class: "vertical"} }) do |f|
  = f.input :name
  = f.submit @company.new_record? ? "Create Company" : "Update Company"

app/views/companies/_sidebar.html.haml
%ul 
  = display_login_messages
  %li= link_to "All companies", companies_path
  %li= link_to "New company", new_company_path

app/views/companies/edit.html.haml
%h1 Edit 

= render "layouts/error_notification", object: @company

= render "form"

- content_for :aside do
  = render "sidebar"

app/views/companies/index.html.haml
%h1 Companies: index
%p Here are all of the companies:

%table 
  %thead 
    %tr 
      %th Company
  %tbody 
    = render partial: "company", collection: @companies
    

- content_for :aside do
  = render "sidebar"

app/views/companies/new.html.haml
%h1 New Company

= render 'layouts/error_notification', object: @company

= render 'form'

- content_for :aside do
  = render 'sidebar'

app/views/companies/show.html.haml
%h1= @company.name

= link_to "Edit company", edit_company_path(@company)

%table
  %thead 
    %tr 
      %th 
        Project
      %th
        Company
  %tbody 
    = render partial: "projects/project", collection: @company.projects

- content_for :aside do
  = render "sidebar"

app/views/layouts/_error_notification.html.haml
- if object.errors.any?
  .errors
    %p
    You have got #{"#{pluralize(object.errors.count, 'error')}"}:
    %ul 
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Timetracker
    %meta{content: "width=device-width, initial scale=1", name: "viewport"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    #container
      %header 
        = link_to content_tag('canvas',"Time Tracker",id: 'logocanvas'), root_path
        %nav 
          %ul 
            - nav_items.each do |nav_item|
              = display_nav_item(nav_item[:display_text], nav_item[:controller_name], nav_item[:url_path])
      %section#main
        %article
          - flash.each do |key, msg|
            %div{class: key == :notice ? 'success' : 'error'}
              = msg 
          = yield
        %aside 
          = yield :aside
      %footer 
        %p 
          Time Tracker is a
          %em Sample Company
          App

app/views/projects/_form.html.haml
= simple_form_for(@project, defaults: { input_html: { class: "vertical"} }) do |f|
  = f.input :name
  = f.input :slug
  = f.input :default_rate
  = f.input :company_id, collection: Company.all, prompt: true
  = f.input :user_id, collection: User.order('last_name, first_name'), prompt: true
  = f.submit @project.new_record? ? "Create Project" : "Update Project"

app/views/projects/_project.html.haml
%tr 
  %td= link_to project, project
  %td= link_to project.company, project.company

app/views/projects/_sidebar.html.haml
%ul 
  %li= link_to "All projects", projects_path
  %li= link_to "New project", new_project_path

app/views/projects/edit.html.haml
%h1 Edit 

= render "layouts/error_notification", object: @project

= render "form"

- content_for :aside do
  = render "sidebar"

app/views/projects/index.html.haml
%h1 Projects#index
%p Here are all of the projects:

%table
  %thead 
    %tr 
      %th 
        Project
      %th
        Company
  %tbody 
    = render partial: "project", collection: @projects

- content_for :aside do
  = render "sidebar"

app/views/projects/new.html.haml
%h1 New Project

= render 'layouts/error_notification', object: @project

= render 'form'

- content_for :aside do 
  = render 'sidebar'

app/views/projects/show.html.haml
%h1= @project.name

= link_to "Edit project", edit_project_path(@project)

%p= "Company: #{@project.company}"
%p= "Default rate: #{@project.default_rate}"
%p= "Slug #{@project.slug}"
%p= "Owner #{@project.user}"


%table 
  %thead 
    %tr 
      %th View
      %th User
      %th Project
      %th Date/Time
      %th Hours
  %tbody 
    = render partial: "works/work", collection: @project.works

- content_for :aside do
  = render "sidebar"

app/views/works/_form.html.haml
= simple_form_for(@work, html: {multipart: true}, defaults: { input_html: { class: "vertical"}}) do |f|
  = f.input :project_id, collection: Project.all, prompt: true
  = f.input :date_time_performed, as: :date, label: "Date/Time performed"
  = f.input :hours, collection: 1..8, prompt: true
  = f.input :doc, as: :file, label: "Notes(optional)"
  = f.submit @work.new_record? ? "Create Work" : "Update Work"

app/views/works/_sidebar.html.haml
%ul 
  %li= link_to "All works", works_path
  %li= link_to "New work", new_work_path

app/views/works/_work.html.haml
%tr  
  %td= link_to "View", work
  %td= work.user
  %td= link_to work.project, work.project
  %td= work.date_time_performed.strftime('%d/%m/%Y %H:%M')
  %td= work.hours

app/views/works/edit.html.haml
%h1 Edit 

= render "layouts/error_notification", object: @work

= render "form"

- content_for :aside do
  = render "sidebar"

app/views/works/index.html.haml
%h1 Works#index
%p Here are all of the works:

%table 
  %thead 
    %tr 
      %th View
      %th User
      %th Project
      %th Date/Time
      %th Hours
  %tbody 
    = render partial: "work", collection: @works
= will_paginate @works

- content_for :aside do
  = render "sidebar"
      

app/views/works/new.html.haml
%h1 New Work

= render 'layouts/error_notification', object: @work

= render "form"

- content_for :aside do
  = render 'sidebar'

app/views/works/show.html.haml
%h1= @work.date_time_performed

= link_to "Edit work", edit_work_path(@work)

%p= "Project: #{@work.project.name}"
%p= "User: #{@work.user}"
%p= "Hours: #{@work.hours}"
- if @work.doc
  %p
    Document #{link_to @work.doc, "/uploads/#{@work.doc}", target: "_blank"}

- content_for :aside do
  = render "sidebar"